[package]
name = "ncm-api"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
aes = "0.9.2"
base64 = { workspace = true }
lofty = "0.25.0"
md-5 = { workspace = true }
percent-encoding = "2.3.2"
rand = { workspace = true }
reqwest = { workspace = true, features = ["charset", "gzip", "json", "stream"] }
rsa = { version = "0.9.10", features = ["pem"] }
tokio = { workspace = true, features = ["fs"] }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
qrcode = "0.14.1"
rustls = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
